apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: artifacts.artifact.apicur.io
spec:
  group: artifact.apicur.io
  names:
    kind: Artifact
    plural: artifacts
    singular: artifact
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              isReady:
                type: boolean
              error:
                type: string
              groupId:
                type: string
              artifactId:
                type: string
              version:
                type: string
              globalId:
                type: number
            type: object
          spec:
            properties:
              groupId:
                type: string
              artifactId:
                type: string
              version:
                type: string
              name:
                type: string
              description:
                type: string
              modifiedBy:
                type: string
              modifiedOn:
                type: string
              globalId:
                type: number
              contentId:
                type: number
              type:
                type: string
              state:
                type: string
              labels:
                items:
                  type: string
                type: array
              properties:
                type: object
              content:
                type: string
              externalContent:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
