apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apicurio-registry-kube-sync
subjects:
  - kind: ServiceAccount
    name: apicurio-registry-kube-sync
roleRef:
  kind: Role
  name: apicurio-registry-kube-sync
  apiGroup: rbac.authorization.k8s.io