# permissions for end users to view apicurios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apicurio-viewer-role
rules:
- apiGroups:
  - artifact.w3tec.ch
  resources:
  - apicurios
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - artifact.w3tec.ch
  resources:
  - apicurios/status
  verbs:
  - get
