
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - artifact.w3tec.ch
  resources:
  - apicurios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - artifact.w3tec.ch
  resources:
  - apicurios/finalizers
  verbs:
  - update
- apiGroups:
  - artifact.w3tec.ch
  resources:
  - apicurios/status
  verbs:
  - get
  - patch
  - update
